# -*- coding: utf-8 -*-
"""2_Production_Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_3XvDnlfdfkTv9S_2V7kZCvvMS9pcWai
"""

import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="Production Dashboard", layout="wide")
st.title("📊 Production Dashboard")

uploaded_file = st.file_uploader("Upload Scheduled Excel File", type="xlsx")

if uploaded_file:
    df = pd.read_excel(uploaded_file)

    if "Units Produced" not in df.columns:
        st.warning("⚠️ Uploaded file does not contain schedule data.")
    else:
        # Styling
        st.markdown("""
            <style>
                .metric-label { font-weight: bold; font-size: 18px; color: #2c3e50; }
                .block-container { padding-top: 1rem; }
            </style>
        """, unsafe_allow_html=True)

        st.subheader("📌 Key Metrics")
        col1, col2, col3 = st.columns(3)
        col1.metric("📦 Units Produced", f"{df['Units Produced'].sum():,}")
        col2.metric("🔁 Batches", df[df["Stage"] == "Produce"].shape[0])
        col3.metric("📅 Days Used", df["Date"].nunique())

        st.subheader("📈 Daily Production Chart")
        daily = df[df["Stage"] == "Produce"].groupby("Date")["Units Produced"].sum().reset_index()
        fig = px.bar(daily, x="Date", y="Units Produced", title="Units Produced Per Day")
        st.plotly_chart(fig, use_container_width=True)

        st.subheader("🧾 Full Schedule Table")
        st.dataframe(df, use_container_width=True)